version: '3'

volumes:
    storage:
services:

  map_service:
    build: thomas-mcnutt-service/
    depends_on:
      - 'database'
    ports:
      - '3003:3003'

  database:
    container_name: 'mongo'
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - 'storage:/data/db'